/**
 * Все игровые таблицы: костюм, камера, пассивный доход, предметы, скины, кадры, достижения.
 * Цены скинов и премиум-покупок уменьшены вдвое и указаны в рублях (по просьбе заказчика).
 */

export const SAVE_KEY = 'spiderman_tycoon_save_v1'

/** Стоимость перехода НА этот уровень (индекс = уровень). Уровень 1 уже открыт. */
export const COSTUME_LEVELS = [
  null,
  {
    level: 1,
    name: 'Порванный костюм',
    cost: 0,
    heroBonus: 0,
    slots: 1,
    duration: 15,
    superChance: 0,
    spawnBonus: 0,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#b33939', accent: '#1e3a8a', glow: 'transparent' },
  },
  {
    level: 2,
    name: 'Починенный',
    cost: 40,
    heroBonus: 0.2,
    slots: 1,
    duration: 15,
    superChance: 0,
    spawnBonus: 0,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#dc2626', accent: '#1d4ed8', glow: 'transparent' },
  },
  {
    level: 3,
    name: 'Улучшенная ткань',
    cost: 90,
    heroBonus: 0.5,
    slots: 2,
    duration: 15,
    superChance: 0.05,
    spawnBonus: 0,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#ef4444', accent: '#2563eb', glow: '#fca5a5' },
  },
  {
    level: 4,
    name: 'Кевларовая броня',
    cost: 180,
    heroBonus: 0.8,
    slots: 2,
    duration: 20,
    superChance: 0.05,
    spawnBonus: 0,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#7f1d1d', accent: '#1e3a8a', glow: '#fbbf24' },
  },
  {
    level: 5,
    name: 'Электрошок',
    cost: 350,
    heroBonus: 1.2,
    slots: 2,
    duration: 20,
    superChance: 0.1,
    spawnBonus: 0,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#1d4ed8', accent: '#facc15', glow: '#38bdf8' },
  },
  {
    level: 6,
    name: 'Паучий сенсор',
    cost: 650,
    heroBonus: 1.6,
    slots: 2,
    duration: 20,
    superChance: 0.1,
    spawnBonus: 0.15,
    superMult: 1,
    spaceBg: false,
    colors: { body: '#6d28d9', accent: '#f8fafc', glow: '#c4b5fd' },
  },
  {
    level: 7,
    name: 'Нанотехнологии',
    cost: 1200,
    heroBonus: 2.0,
    slots: 2,
    duration: 20,
    superChance: 0.1,
    spawnBonus: 0.15,
    superMult: 2,
    spaceBg: false,
    colors: { body: '#111827', accent: '#ef4444', glow: '#22d3ee' },
  },
  {
    level: 8,
    name: 'Железный паук',
    cost: 2200,
    heroBonus: 2.5,
    slots: 2,
    duration: 30,
    superChance: 0.1,
    spawnBonus: 0.15,
    superMult: 2,
    spaceBg: false,
    colors: { body: '#b45309', accent: '#fde047', glow: '#fdba74' },
  },
  {
    level: 9,
    name: 'Космический паук',
    cost: 4000,
    heroBonus: 3.2,
    slots: 2,
    duration: 30,
    superChance: 0.3,
    spawnBonus: 0.15,
    superMult: 2,
    spaceBg: true,
    colors: { body: '#4c1d95', accent: '#e0e7ff', glow: '#a78bfa' },
  },
  {
    level: 10,
    name: 'Абсолютный паук',
    cost: 7500,
    heroBonus: 4.0,
    slots: 2,
    duration: 30,
    superChance: 0.3,
    spawnBonus: 0.15,
    superMult: 3,
    spaceBg: true,
    colors: { body: '#e11d48', accent: '#fbbf24', glow: '#f472b6' },
  },
]

export const CAMERA_LEVELS = [
  null,
  {
    level: 1,
    name: 'Старая плёночная',
    cost: 0,
    photoBonus: 0,
    frameScale: 1,
    speed: 1,
    shots: 3,
    rareBonus: 0,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 2,
    name: 'Цифровая',
    cost: 30,
    photoBonus: 0.2,
    frameScale: 1.22,
    speed: 1,
    shots: 3,
    rareBonus: 0,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 3,
    name: 'Профессиональная',
    cost: 70,
    photoBonus: 0.5,
    frameScale: 1.22,
    speed: 0.78,
    shots: 3,
    rareBonus: 0,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 4,
    name: 'С телеобъективом',
    cost: 150,
    photoBonus: 1.0,
    frameScale: 1.22,
    speed: 0.78,
    shots: 3,
    rareBonus: 0.1,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 5,
    name: 'Сверхскоростная',
    cost: 280,
    photoBonus: 1.5,
    frameScale: 1.22,
    speed: 0.78,
    shots: 4,
    rareBonus: 0.1,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 6,
    name: 'Дрон-камера',
    cost: 500,
    photoBonus: 2.0,
    frameScale: 1.48,
    speed: 0.58,
    shots: 4,
    rareBonus: 0.1,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 7,
    name: 'Голографическая',
    cost: 900,
    photoBonus: 2.5,
    frameScale: 1.48,
    speed: 0.58,
    shots: 4,
    rareBonus: 0.2,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 8,
    name: 'Квантовая',
    cost: 1600,
    photoBonus: 3.0,
    frameScale: 1.48,
    speed: 0.58,
    shots: 5,
    rareBonus: 0.2,
    perfectMult: 1,
    alwaysRarePerfect: false,
  },
  {
    level: 9,
    name: 'Мультивселенская',
    cost: 3000,
    photoBonus: 3.5,
    frameScale: 1.48,
    speed: 0.58,
    shots: 5,
    rareBonus: 0.2,
    perfectMult: 2,
    alwaysRarePerfect: false,
  },
  {
    level: 10,
    name: 'Абсолютная камера',
    cost: 5500,
    photoBonus: 4.0,
    frameScale: 1.55,
    speed: 0.52,
    shots: 6,
    rareBonus: 0.2,
    perfectMult: 2,
    alwaysRarePerfect: true,
  },
]

export const PASSIVE_LEVELS = [
  null,
  { level: 1, name: 'Старый ноутбук', cost: 0, perMin: 1, maxHours: 1 },
  { level: 2, name: 'Блог о фотографии', cost: 60, perMin: 2, maxHours: 1.5 },
  { level: 3, name: 'Видеоблог', cost: 140, perMin: 4, maxHours: 2 },
  { level: 4, name: 'Онлайн-курсы', cost: 280, perMin: 8, maxHours: 2.5 },
  { level: 5, name: 'Партнёрские программы', cost: 500, perMin: 12, maxHours: 3 },
  { level: 6, name: 'Собственный сайт', cost: 900, perMin: 18, maxHours: 4 },
  { level: 7, name: 'Реклама в блоге', cost: 1600, perMin: 25, maxHours: 5 },
  { level: 8, name: 'Спонсорство', cost: 2800, perMin: 35, maxHours: 6 },
  { level: 9, name: 'Инвестиции', cost: 5000, perMin: 50, maxHours: 7 },
  { level: 10, name: 'Финансовая империя', cost: 9000, perMin: 80, maxHours: 8 },
]

export const ROOM_ITEMS = [
  { id: 'bed', name: 'Новая кровать', emoji: '🛏️', cost: 150, desc: '+5% к общему доходу' },
  { id: 'laptop', name: 'Новый ноутбук', emoji: '💻', cost: 400, desc: '+1 уровень пассивного дохода' },
  { id: 'poster', name: 'Постер на стену', emoji: '🖼️', cost: 100, desc: '+3% к доходу с фото' },
  { id: 'carpet', name: 'Ковёр', emoji: '🧶', cost: 120, desc: '+3% к доходу с геройства' },
  { id: 'tv', name: 'Телевизор', emoji: '📺', cost: 300, desc: 'Раз в день +200 монет за рекламу' },
  { id: 'lamp', name: 'Лампа', emoji: '💡', cost: 80, desc: '+2% к общему доходу' },
  { id: 'shelf', name: 'Полка для книг', emoji: '📚', cost: 180, desc: '+5% к пассивному доходу' },
  { id: 'fridge', name: 'Мини-холодильник', emoji: '🧊', cost: 220, desc: '+5% к общему доходу' },
  { id: 'plant', name: 'Растение', emoji: '🪴', cost: 60, desc: '+2% к фото и геройству' },
]

/** Бесплатные (за монеты) скины. Цены в 2 раза ниже исходных. */
export const COIN_SKINS = [
  { id: 'noir', name: 'Нуар', emoji: '⬛', cost: 250, photo: 0.15, hero: 0, all: 0, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+15% к фото', colors: { body: '#111111', accent: '#f5f5f5', glow: '#9ca3af' } },
  { id: 'punk', name: 'Панк-паук', emoji: '🎸', cost: 400, photo: 0, hero: 0, all: 0.1, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+10% к общему доходу', colors: { body: '#0f172a', accent: '#fb7185', glow: '#f43f5e' } },
  { id: 'symbiote', name: 'Симбиот', emoji: '🖤', cost: 600, photo: -0.1, hero: 0.25, all: 0, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+25% к геройству, −10% к фото', colors: { body: '#020617', accent: '#f8fafc', glow: '#22c55e' } },
  { id: 's2099', name: 'Костюм 2099', emoji: '🔮', cost: 750, photo: 0.2, hero: 0.2, all: 0, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+20% к фото и геройству', colors: { body: '#f8fafc', accent: '#be123c', glow: '#fb7185' } },
  { id: 'cartoon', name: 'Мультяшный', emoji: '🎨', cost: 500, photo: 0, hero: 0, all: 0, spawn: 0.2, spaceBg: false, contrast: false, rainbow: false, desc: 'Цели появляются на 20% быстрее', colors: { body: '#f97316', accent: '#2563eb', glow: '#fde047' } },
]

/** Платные скины. Цены в рублях, в 2 раза ниже долларовых. */
export const PAID_SKINS = [
  { id: 'gold', name: 'Золотой паук', emoji: '🥇', priceRub: 49, productId: 'skin_gold', photo: 0, hero: 0, all: 0.3, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+30% к общему доходу', colors: { body: '#eab308', accent: '#78350f', glow: '#fde047' } },
  { id: 'knight', name: 'Паук-рыцарь', emoji: '🛡️', priceRub: 75, productId: 'skin_knight', photo: 0.1, hero: 0.2, all: 0, spawn: 0, spaceBg: false, contrast: false, rainbow: false, desc: '+20% к геройству, +10% к фото', colors: { body: '#94a3b8', accent: '#7f1d1d', glow: '#e2e8f0' } },
  { id: 'cosmic', name: 'Космический паук', emoji: '🌌', priceRub: 99, productId: 'skin_cosmic', photo: 0, hero: 0.4, all: 0, spawn: 0, spaceBg: true, contrast: false, rainbow: false, desc: '+40% к геройству, фон миссий — космос', colors: { body: '#312e81', accent: '#c4b5fd', glow: '#818cf8' } },
  { id: 'invisible', name: 'Паук-невидимка', emoji: '👻', priceRub: 75, productId: 'skin_invisible', photo: 0.25, hero: 0, all: 0, spawn: 0, spaceBg: false, contrast: true, rainbow: false, desc: '+25% к фото, объекты контрастнее', colors: { body: '#67e8f9', accent: '#ecfeff', glow: '#22d3ee' } },
  { id: 'rainbow', name: 'Радужный паук', emoji: '🌈', priceRub: 49, productId: 'skin_rainbow', photo: 0.15, hero: 0.15, all: 0.15, spawn: 0, spaceBg: false, contrast: false, rainbow: true, desc: '+15% ко всему, костюм переливается', colors: { body: '#ef4444', accent: '#22c55e', glow: '#fbbf24' } },
]

export const PREMIUM = {
  disableAds: { productId: 'disable_ads', priceRub: 99, name: 'Отключение рекламы' },
}

export const PHOTOS = [
  { id: 'sunset', name: 'Паук на фоне заката', emoji: '🌅' },
  { id: 'kitten', name: 'Спасение котёнка', emoji: '🐱' },
  { id: 'chase', name: 'Погоня за злодеем', emoji: '🏃' },
  { id: 'police', name: 'Паук и полиция', emoji: '🚓' },
  { id: 'rooftop', name: 'Паук на крыше небоскрёба', emoji: '🏙️' },
  { id: 'selfie', name: 'Селфи с фанатами', emoji: '🤳' },
]

export const ACHIEVEMENTS = [
  { id: 'first_earn', name: 'Первый заработок', desc: 'Заработать 10 монет', reward: 20, emoji: '🪙' },
  { id: 'photo_master', name: 'Мастер кадра', desc: 'Сделать 10 идеальных фото', reward: 100, emoji: '📸' },
  { id: 'savior', name: 'Спаситель города', desc: 'Спасти 50 мирных жителей', reward: 150, emoji: '😊' },
  { id: 'hunter', name: 'Обезвреживатель', desc: 'Поймать 50 преступников', reward: 150, emoji: '😈' },
  { id: 'collector', name: 'Коллекционер', desc: 'Повесить 3 редких кадра', reward: 100, emoji: '🖼️' },
  { id: 'millionaire', name: 'Миллионер', desc: 'Накопить 5000 монет', reward: 300, emoji: '💰' },
  { id: 'dresser', name: 'Костюмер', desc: 'Купить первый альтернативный скин', reward: 200, emoji: '🧥' },
  { id: 'passive_5', name: 'Пассивный доход', desc: '5-й уровень пассивного дохода', reward: 500, emoji: '📈' },
  { id: 'finance_genius', name: 'Финансовый гений', desc: '10-й уровень пассивного дохода', reward: 1000, emoji: '🏆' },
]

export const PHOTO_SUBJECTS = [
  { id: 'hero', emoji: '🕷️', label: 'Герой в полёте', color: '#dc2626' },
  { id: 'villain', emoji: '🦹', label: 'Злодей', color: '#7c3aed' },
  { id: 'car', emoji: '🚗', label: 'Машина', color: '#2563eb' },
  { id: 'heli', emoji: '🚁', label: 'Вертолёт', color: '#0f766e' },
  { id: 'cat', emoji: '🐱', label: 'Котёнок', color: '#d97706' },
  { id: 'goblin', emoji: '🎃', label: 'Зелёный гоблин', color: '#16a34a' },
]

export function getSkinById(id) {
  return COIN_SKINS.find((s) => s.id === id) || PAID_SKINS.find((s) => s.id === id) || null
}

export function allSkins() {
  return [...COIN_SKINS, ...PAID_SKINS]
}
